// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUujqCvy762xLGreiWYtyQ8-EnONNsDe4',
    appId: '1:261447006503:web:ec8bb95836e07844bf5102',
    messagingSenderId: '261447006503',
    projectId: 'food-explorer-197ea',
    authDomain: 'food-explorer-197ea.firebaseapp.com',
    storageBucket: 'food-explorer-197ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKDZo1g8uNqTTMb-pkHysMO_YL0UFnZw0',
    appId: '1:261447006503:android:4bf6f6c36684e3d9bf5102',
    messagingSenderId: '261447006503',
    projectId: 'food-explorer-197ea',
    storageBucket: 'food-explorer-197ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgELFLxhqkc_4yapUQ6Cl9HawhMr7b_w8',
    appId: '1:261447006503:ios:2e79f633763ceb51bf5102',
    messagingSenderId: '261447006503',
    projectId: 'food-explorer-197ea',
    storageBucket: 'food-explorer-197ea.firebasestorage.app',
    iosBundleId: 'com.example.foodExplorer',
  );
}
